name: "local-action"
description: Grading action for local exercise
author: githubtraining
inputs:
  event_ctx:
    description: event object from the github context
    required: true

runs:
  -name: Publish package
  run: npm publish
