name: "local-action"
description: Grading action for local exercise
author: githubtraining
inputs:
  event_ctx:
    description: event object from the github context
    required: true

runs:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v1
  - run: npm ci
  - run: npm publish
